FileVersion = 1
Projects = {Ari2D-Tutorial = {Path = "."}, Ariyana_beef = {Path = "../ariyana/Beef"}, JSON_Beef = {Path = "../ariyana/Beef/deps/JSON_Beef/lib"}, CurlBeef = {Path = "../CurlBeef"}, BeefExtensionsLib = {Path = "../ariyana/Beef/deps/Beef-Extensions-Lib"}}

[Workspace]
StartupProject = "Ari2D-Tutorial"
